FROM python

RUN apt update

RUN apt install git

RUN git clone https://github.com/Antoniorios17/kuralabs_deployment_3.git

WORKDIR /kuralabs_deployment_3

RUN pip install -r  requirements.txt

EXPOSE 5000

ENTRYPOINT FLASK_APP=application flask run --host=0.0.0.0
